services:

  pml0015:
    build: ./pml0015
    container_name: pml0015
    expose:
      - "8081"
    networks:
      - webnet

  bai0002:
    build: ./bai0002
    container_name: bai0002
    expose:
      - "8081"
    networks:
      - webnet

  ccb0016:
    build: ./ccb0016
    container_name: ccb0016
    expose:
      - "8081"
    networks:
      - webnet

  sjp0005:
    build: ./sjp0005
    container_name: sjp0005
    expose:
      - "8081"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pml0015
      - bai0002
      - ccb0016
      - sjp0005
    networks:
      - webnet

networks:
  webnet:
